package app.entities.userside.artist;

import app.entities.userside.artist.Artist;
import lombok.Getter;
import lombok.Setter;

import java.util.HashMap;
import java.util.Map;

/**
 * The Monetization class represents the monetization system for an Artist.
 * It tracks revenue generated from songs and merchandise, as well as the most profitable song.
 */
@Getter
@Setter
public class Monetization {
    private Artist artist;
    private Boolean interacted;

    private Double songRevenue;
    private Double merchRevenue;
    private String mostProfitableSong;

    private HashMap<String, Double> revenuePerSong;

    /**
     * Initializes a new instance of the Monetization class for a given Artist.
     *
     * @param artist The Artist for which monetization is being tracked.
     */
    public Monetization(final Artist artist) {
        this.songRevenue = 0.0;
        this.merchRevenue = 0.0;
        this.mostProfitableSong = "N/A";

        this.artist = artist;
        this.interacted = false;

        this.revenuePerSong = new HashMap<>();
    }

    /**
     * Marks interaction with the monetization system.
     */
    public void interact() {
        this.interacted = true;
    }

    /**
     * Adds song revenue to the total song revenue.
     *
     * @param revenue The revenue generated by a song.
     */
    public void addSongRevenue(final Double revenue) {
        this.songRevenue += revenue;
    }

    /**
     * Adds revenue generated by a specific song to the revenuePerSong map.
     *
     * @param song    The name of the song.
     * @param revenue The revenue generated by the song.
     */
    public void addRevenuePerSong(final String song, final Double revenue) {
        Double currentRevenue = revenuePerSong.getOrDefault(song, 0.0);
        currentRevenue += revenue;
        this.revenuePerSong.put(song, currentRevenue);
    }

    /**
     * Finds the key with the highest value in the revenuePerSong map.
     *
     * @return The name of the song with the highest revenue.
     */
    private String getKeyWithHighestValue() {
        // chatGPT wrote this when I asked for a function that gets the highest value in a hashmap
        String keyWithHighestValue = null;
        double highestValue = Double.MIN_VALUE;

        for (Map.Entry<String, Double> entry : revenuePerSong.entrySet()) {
            double currentValue = entry.getValue();
            String currentKey = entry.getKey();

            // Check if the current value is greater than the highest value found so far
            if (currentValue > highestValue) {
                highestValue = currentValue;
                keyWithHighestValue = currentKey;
            }
            // If the current value is equal to the highest value, compare keys alphabetically
            else if (currentValue == highestValue && keyWithHighestValue != null) {
                if (currentKey.compareTo(keyWithHighestValue) < 0) {
                    keyWithHighestValue = currentKey;
                }
            }
        }

        return keyWithHighestValue;
    }

    /**
     * Determines the most profitable song based on revenue.
     */
    public void decideMostProfitableSong() {
        this.mostProfitableSong = getKeyWithHighestValue();
    }

    /**
     * Marks interaction with the monetization system and adds merchandise revenue.
     *
     * @param price The price of the merchandise.
     */
    public void payMerch(final Double price) {
        interacted = true;
        merchRevenue += price;
    }
}
